language: ruby
rvm:
- 2.6.1
script:
- bundle install --jobs=3 --retry=3
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
before_install:
- gem update --system
- gem --version
- gem install bundler
bundler_args: "--without production"
env:
- rack=1.3.4
- rack=master
- tilt=1.3.3
- tilt=master
- CHEF_VERSION=14.3.37
deploy:
  provider: heroku
  api_key:
    secure: UZBUz1hkzs6DHnmI+lJhwGpXDJC8ARWC85upAqxiQAgxw2iuGmrayCZfavz7mWAOmCInt87tdVAUdcwRnxbNTS2DokDsRl9RDPpYteI+tha8YXvsQyGrImleF3cZ8OS1O9n35khCK/OF3CJvxH75ioNEsQSFDYEKJo3l8gP9LZ6khv3/sxTIfa7p+Zg8N2cFCuP24qO7T5k2Hll5kFKn+GmOu3KLRfG+LxSRLjjjt96/dc3plN6h9MdVTLZetM/E2rqxA0i8jqRNumvTB9qe3yWEO3fG2KgrdF/jF3bj519OQ94FRAsYHNllw8ttp1L2/nZD0yRnu9Y6D5ansfFkvWa8gZdAqVIZTiUbYSbxXb9KjZ55OwyA1Sd8xL9rfFUaz0wYkrfQjMHgHoGd46KNIMLOewdvC7iQEpwggItgw8fcxlMY6kgQSO7Jvz2vhverYwkpWf2CA39CpxPoGbEYP+Mvd6zQuDqLERsxqW0ju3KLF5sR9pMuyT3LUdvGFfw0YHLtrmpMJnUMHnRnNs5ZOcIhJRK++KS/xfBRHpjr3ocNIpj4q/JkFj6B/RRkAh+CSW9A0jPBnm5kkTQGESD2T+4sTPAIaPjbOKJoh6XnyZ57FthN8K+UANVsH4N1NXZUfIHDzCZOEFpRQhL9nK5iha+8hoZ37mx+MH7XMMgYwJI=
  app: bayano-rails-tutorial-hello
  run: "rake db:migrate"

