language: ruby
rvm:
  - 2.6.1
  - trufflerruby
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
bundler_args: --without production
env:
  - "rack=1.3.4"
  - "rack=master"
  - "tilt=1.3.3"
  - "tilt=master"
  - CHEF_VERSION=14.3.37



